name: cuccinare
description: "Una aplicacion de recetas"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  assets: ^0.0.1
  flutter:
    sdk: flutter
  go_router: ^14.1.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
